site_name: niri
docs_dir: wiki
site_url: https://yalter.github.io/niri
repo_url: https://github.com/YaLTeR/niri
edit_uri: edit/main/docs/wiki/
use_directory_urls: false

theme:
  name: material
  logo: _assets/icons/logo.svg
  favicon: _assets/icons/logo.svg
  features:
    - navigation.instant
    - search.suggest
    - content.code.copy
    - content.action.edit
  palette:
    - media: "(prefers-color-scheme)"
      primary: custom
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      primary: custom
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: custom
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
markdown_extensions:
  - github-callouts
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.keys
  - toc:
      permalink: '#'
  - attr_list
plugins:
  - search:
      separator: '[\s\u200b\-]'
hooks:
  - hooks/shortcodes.py
  - hooks/remove-must-fail.py
extra_css:
  - _assets/stylesheets/niri.css
strict: true
validation:
  nav:
    omitted_files: warn
    not_found: warn
    absolute_links: relative_to_docs
  links:
    not_found: warn
    anchors: warn
    absolute_links: relative_to_docs
    unrecognized_links: warn
not_in_nav: |
  _Sidebar.md
  Configuration:-Overview.md
  README.md
# ah, wouldn't it be nice if we could autogenerate this with wiki/_Sidebar.md
nav:
  - 使用指南:
    - 快速入门: Getting-Started.md
    - systemd 配置示例: Example-systemd-Setup.md
    - 重要软件: Important-Software.md
    - 工作区: Workspaces.md
    - 浮动窗口: Floating-Windows.md
    - 标签页: Tabs.md
    - 桌面概览: Overview.md
    - 屏幕录制: Screencasting.md
    - Layer-Shell 组件: Layer-Shell-Components.md
    - IPC, niri msg: IPC.md
    - 应用程序特定问题: Application-Issues.md
    - Nvidia: Nvidia.md
    - Xwayland: Xwayland.md
    - 手势操作: Gestures.md
    - 打包 niri: Packaging-niri.md
    - 集成 niri: Integrating-niri.md
    - 无障碍: Accessibility.md
    - 名称与徽标: Name-and-Logo.md
    - 常见问题: FAQ.md
  - 配置:
    - 简介: Configuration:-Introduction.md
    - 输入: Configuration:-Input.md
    - 输出: Configuration:-Outputs.md
    - 按键绑定: Configuration:-Key-Bindings.md
    - 开关事件: Configuration:-Switch-Events.md
    - 布局: Configuration:-Layout.md
    - 命名工作区: Configuration:-Named-Workspaces.md
    - 杂项: Configuration:-Miscellaneous.md
    - 窗口规则: Configuration:-Window-Rules.md
    - 图层规则: Configuration:-Layer-Rules.md
    - 动画: Configuration:-Animations.md
    - 手势: Configuration:-Gestures.md
    - 调试选项: Configuration:-Debug-Options.md
    - 包含: Configuration:-Include.md
  - Development:
    - Design Principles: Development:-Design-Principles.md
    - Developing niri: Development:-Developing-niri.md
    - Documenting niri: Development:-Documenting-niri.md
    - Fractional Layout: Development:-Fractional-Layout.md
    - Redraw Loop: Development:-Redraw-Loop.md
    - Animation Timing: Development:-Animation-Timing.md
